[tool.poetry]
name = "agsm-middleware"
version = "0.1.0"
description = ""
authors = ["Okan Celik <okan.celik@cgi.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
